merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    # path('bands/<int:band_id>/listings/', views.manage_band_listings, name='manage-band-listings'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/update/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete/', views.listing_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('email_sent/', views.email_sent, name='email-sent'),
    path('about-us/', views.about, name='about'),
]

merchex/listings/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.
class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    # like_new = models.fields.BooleanField(default=False) <-- SUPPRIMER CETTE LIGNE second stratégy

    def __str__(self):
        # return f'{self.__class__.__name__} object ({self.id}) ({self.name})'
        return f'{self.name}'


class Listing(models.Model):

    TYPE_CHOICES = [
        ('Records', 'Records'),
        ('Clothing', 'Clothing'),
        ('Posters', 'Posters'),
        ('Miscellaneous', 'Miscellaneous'),
    ]

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    year = models.fields.IntegerField(null=True, blank=True)
    sold = models.fields.BooleanField(default=False)
    type = models.CharField(choices=TYPE_CHOICES, max_length=20, default='Records')
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from django import forms
from .models import Band, Listing


class ContactUsForm(forms.Form):
    
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)
   
   
class BandForm(forms.ModelForm):
    
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')  # if  null=True &/or default=T/F


class ListingForm(forms.ModelForm):
    
    class Meta:
        model = Listing
        # fields = '__all__'
        exclude = ('sold', 'year')  # if  null=True &/or default=T/F

merchex/listings/views.py
# from django.http import HttpResponse
# from listings.models import Band
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Band, Listing
from .forms import ContactUsForm, BandForm, ListingForm


# Create your views here.
def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', context={'bands': bands})


def band_detail(request, band_id):
    # to recover the band(obj) and handle the case where the object does not exist.
    try:
        band = Band.objects.get(id=band_id)
    except Band.DoesNotExist:
        raise Http404("No Band matches the given query.")
    
    # context = {'id': band_id} we pass the id to the model
    context = {'band': band}  # to pass the band to the template
    return render(request, 'listings/band_detail.html', context)


def listing_list(request):
    listings = Listing.objects.all()
    context = {'listings': listings}
    return render(request, 'listings/listing_list.html', context)


def listing_detail(request, listing_id):
    # to recover the listing(obj) and handle the case where the object does not exist.
    listing = get_object_or_404(Listing, id=listing_id)
    context = {'listing': listing}
    return render(request, 'listings/listing_detail.html', context)


def about(request):
    return render(request, 'listings/about.html')


def contact(request):
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)

    if request.method == 'POST':
        # Create an instance of our form and fill it with the POST data
        form = ContactUsForm(request.POST)
        
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            # Redirect to confirmation page
            return redirect('email-sent')  # We can redirect the browser from the original page to a new page
        
    # if the form is invalid, we let execution continue until return
    # below and display the form again (with errors).
    else:
        # this must be a GET request, so create an empty form
        form = ContactUsForm()    # Add a new form here
        
    context = {'form': form}  # pass this form to the template
    return render(request, 'listings/contact.html', context)


def email_sent(request):
    return render(request, 'listings/email_sent.html')


def band_create(request):
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        # Create an instance of our form and fill it with the POST data
        form = BandForm(request.POST)
        
        if form.is_valid():
            # create a new “Band” and save it in the database
            band = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the arguments of the url pattern as arguments to the redirect function
            return redirect('band-detail', band.id)
        
    # if the form is invalid, we let execution continue until return
    # below and display the form again (with errors).
    else:
        # this must be a GET request, so create an empty form
        form = BandForm()  # Add a new BandForm empty here if request.GET
    
    context = {'form': form}  # pass this form to the template
    return render(request, 'listings/band_create.html', context)


def listing_create(request):
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        # Create an instance of our form and fill it with the POST data
        form = ListingForm(request.POST)
        
        if form.is_valid():
            # create a new “Listing” and save it in the database
            listing = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the arguments of the url pattern as arguments to the redirect function
            return redirect('listing-detail', listing.id)
    
    # if the form is invalid, we let execution continue until return
    # below and display the form again (with errors).
    else:
        # this must be a GET request, so create an empty form
        form = ListingForm()  # Add a new ListingForm empty here if request.GET
    
    context = {'form': form}  # pass this form to the template
    return render(request, 'listings/listing_create.html', context)


def band_update(request, band_id):
    band = Band.objects.get(id=band_id)
    
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        # we pre-fill the form with an existing band the instance already created and fill it with the POST data
        form = BandForm(request.POST, instance=band)
        
        if form.is_valid():
            # update the instance of the object already created “Band” and save it in the database
            band = form.save()
            # redirect to the detail page of the band we just update
            # we can provide the arguments of the url pattern as arguments to the redirect function
            return redirect('band-detail', band.id)
    
    # if the form is invalid, we let execution continue until return
    # below and display the form again (with errors).
    else:
        # we pre-fill the form with an existing band the instance already created
        # this must be a GET request, so open with the instance of the object already created
        form = BandForm(instance=band)  # we pre-fill the form with an existing band here if request.GET
    
    context = {'form': form}  # pass this form to the template
    return render(request, 'listings/band_update.html', context)


def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        # we pre-fill the form with an existing listing the instance already created and fill it with the POST data
        form = ListingForm(request.POST, instance=listing)
        
        if form.is_valid():
            # update the instance of the object already created “Listing” and save it in the database
            listing = form.save()
            # redirect to the detail page of the listing we just update
            # we can provide the arguments of the url pattern as arguments to the redirect function
            return redirect('listing-detail', listing.id)
    
    # if the form is invalid, we let execution continue until return
    # below and display the form again (with errors).
    else:
        # we pre-fill the form with an existing listing the instance already created
        # this must be a GET request, so open with the instance of the object already created
        form = ListingForm(instance=listing)  # we pre-fill the form with an existing listing here if request.GET
    
    context = {'form': form}  # pass this form to the template
    return render(request, 'listings/listing_update.html', context)


def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        if 'confirm' in request.POST:
            # delete the band object in the database
            band.delete()
            # redirect to the list-page of the band we just verified if existing it
            return redirect('band-list')
        
        elif 'cancel' in request.POST:
            # redirect to the list-page without delete
            return redirect('band-list')
        
    # no need for “else” here. If it's a GET request, just continue
    
    context = {'band': band}  # to pass the band to the template
    return render(request, 'listings/band_delete.html', context)


def listing_delete(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    # Take a look at « request.method » and « request.POST »
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    
    if request.method == 'POST':
        if 'confirm' in request.POST:
            # delete the listing object in the database
            listing.delete()
            # redirect to the list-page of the listing we just verified if existing it
            return redirect('listing-list')
        
        elif 'cancel' in request.POST:
            # redirect to the list-page without delete
            return redirect('listing-list')
    
    # no need for “else” here. If it's a GET request, just continue
    
    context = {'listing': listing}  # to pass the band to the template
    return render(request, 'listings/band_delete.html', context)















# def manage_band_listings(request, band_id, listing_id):
#     # to recover the band(obj) and handle the case where the object does not exist.
#     band = get_object_or_404(Band, id=band_id) # or band = Band.objects.get(id=band_id)
#     listing = get_object_or_404(Listing, id=listing_id)

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}
{% block title %}About us{% endblock title %}
{% block content %}
<h1>About us</h1>
<p>Nous adorons merch !</p>'
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Create a new band</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Send">
</form>
{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Delete a band</h1>
<p>Are you sure you want to delete the band : {{ band.name }}? All of the following related items will be deleted !/p>


<form action="" method="post">
    {% csrf_token %}
    <input type="submit" name="confirm" value="Yes, I’m sure">
    <input class="cancel-link" type="submit" name="cancel" value="No, take me back">
</form>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<!--<h2>L'identifiant est {{ id }}</h2> context={'id': band_id}-->
<h2>{{ band.name }}</h2>

<ul>
  <li>Genre : {{ band.get_genre_display }}</li>
  <li>Année de formation : {{ band.year_formed }}</li>
  <li>Actif : {{ band.active|yesno }}</li>
  {% if band.official_homepage %} <!--because field null=True-->
  <li><a target="_blank" href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
  {% endif %}
</ul>

<p>{{ band.biography }}</p>

<h2>Listings of the band: </h2>
<ul>
    {% for listing in band.listing_set.all %}
        <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
</ul>

<a href="{% url 'band-update' band.id %}">[Edit a band]</a>
<a href="{% url 'band-delete' band.id %}">[Delete a band]</a>
<a href="{% url 'band-list' %}">All Bands : Return to all bands</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Bands</h1>
<a href="{% url 'band-create' %}">Create a new band</a>
<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
          - <a href="{% url 'band-update' band.id %}">[Edit]</a>
          - <a href="{% url 'band-delete' band.id %}">[Delete]</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Update a band</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Send">
</form>
{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %}Merchex{% endblock title %}</title>
        <link href="{% static 'listings/style.css' %}" rel="stylesheet"/>
    </head>
    <body>
        <nav>
        <a href="{% url 'band-list' %}">Bands</a>
        <a href="{% url 'listing-list' %}">listings</a>
        <a href="{% url 'contact' %}">Contact us</a>
        <a href="{% url 'about' %}">About us</a>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}
{% block title %}Confirmation of sending{% endblock title %}
{% block content %}
<h1>thank you !</h1>
<p>Your email has been sent successfully.</p>
<a href="{% url 'contact' %}">Return to form</a>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Create a new Listing</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Send">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Delete a listing</h1>
<p>Are you sure you want to delete the band : {{ listing.name }}? All of the following related items will be deleted !/p>


<form action="" method="post">
    {% csrf_token %}
    <input type="submit" name="confirm" value="Yes, I’m sure">
    <input class="cancel-link" type="submit" name="cancel" value="No, take me back">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{% block title %}Listings{% endblock title %}
{% block content %}
<h2>{{ listing.title }}</h2>

<ul>
  <li>Ad type  : {{ listing.type }}</li>
  {% if listing.year %} <!--because field null=True-->
  <li>Item year : {{ listing.year }}</li>
  {% endif %}
  <li>Sold : {{ listing.sold|yesno }}</li>

  {% if listing.band %}
      <li>Related Band : <a href="">{{ listing.band }}</a></li>
 {% endif %}
</ul>



<p>Description :{{ listing.description }}</p>

<a href="{% url 'listing-update' listing.id %}">[Edit a listing]</a>
<a href="{% url 'listing-delete' listing.id %}">[Delete a listing]</a>
<a href="{% url 'listing-list' %}">All listings : return to listings</a>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}
{% block title %}Listings{% endblock title %}
{% block content %}
<h1>Listings</h1>
<a href="{% url 'listing-create' %}">Create new Listing</a>

<ul>
    {% for listing in listings %}
        <li>
            <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
            <a href="{% url 'listing-update' listing.id %}">[Edit]</a>
            <a href="{% url 'listing-delete' listing.id %}">[Delete]</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Update a listing</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Send">
</form>
{% endblock %}

merchex/listings/templates/listings/manage_band_listings.html
{% extends 'listings/base.html' %}
{% extends 'listings/band_detail.html' %}
{% block content %}
{% endblock %}